In [10]:
import numpy as np

def text_to_matrix(text, n):
    text = text.encode('utf-8')
    text_values = np.array(list(text), dtype=np.uint8)

    target_length = n * n
    padding_length = target_length - len(text_values) % target_length if len(text_values) % target_length != 0 else 0

    padded_text = np.pad(text_values, (0, padding_length), mode='constant', constant_values=0)

    matrix = padded_text.reshape((-1, n)) 
    return matrix

def encrypt_matrix(matrix, key_matrix):
    if matrix.shape[1] != key_matrix.shape[0]:
        raise ValueError("Matrix and key matrix dimensions do not match for multiplication.")
    
    return np.dot(matrix, key_matrix)

def decrypt_matrix(encrypted_matrix, key_matrix_inv):
    return np.dot(encrypted_matrix, key_matrix_inv)

def matrix_to_text(matrix):
    flattened = matrix.flatten()

    text = ''.join(chr(int(round(value))) for value in flattened if value != 0) 
    return text


if __name__ == "__main__":
    with open("file.txt", "r", encoding="utf-8") as file:
        text = file.read()
    
    
    n = 4 
    
    
    matrix = text_to_matrix(text, n)
    print("Original Matrix:")
    print(matrix)

    
    key_matrix = np.random.randint(1, 10, (n, n))
    try:
        key_matrix_inv = np.linalg.inv(key_matrix)
    except np.linalg.LinAlgError:
        print("Key matrix is not invertible. Generating a new key matrix.")
        key_matrix = np.random.randint(1, 10, (n, n))
        key_matrix_inv = np.linalg.inv(key_matrix)

    
    encrypted_matrix = encrypt_matrix(matrix, key_matrix)
    print("Encrypted Matrix:")
    print(encrypted_matrix)

    
    decrypted_matrix = decrypt_matrix(encrypted_matrix, key_matrix_inv)
    print("Decrypted Matrix:")
    print(decrypted_matrix)

    
    decrypted_text = matrix_to_text(decrypted_matrix)
    print("Decrypted Text:")
    print(decrypted_text)


Original Matrix:
[[ 72 101 108 108]
 [111  44  32 116]
 [104 105 115  32]
 [105 115  32  97]
 [ 32 115 101  99]
 [114 101 116  32]
 [109 101 115 115]
 [ 97 103 101  46]
 [ 10 102 114 111]
 [109  32 121 111]
 [117  32 102 114]
 [105 101 110 100]
 [ 32 112 101 116]
 [101 114   0   0]
 [  0   0   0   0]
 [  0   0   0   0]]
Encrypted Matrix:
[[2853  886 1419 2385]
 [2182  638 1331 1612]
 [2515  827 1225 2211]
 [2633  730 1419 2132]
 [2625  795 1202 2264]
 [2545  842 1265 2221]
 [3173  995 1653 2610]
 [2483  795 1226 2151]
 [2550  788 1139 2197]
 [2556  867 1438 2005]
 [2514  832 1455 1938]
 [2999  942 1548 2489]
 [2734  823 1278 2322]
 [1632  430  847 1430]
 [   0    0    0    0]
 [   0    0    0    0]]
Decrypted Matrix:
[[ 7.20000000e+01  1.01000000e+02  1.08000000e+02  1.08000000e+02]
 [ 1.11000000e+02  4.40000000e+01  3.20000000e+01  1.16000000e+02]
 [ 1.04000000e+02  1.05000000e+02  1.15000000e+02  3.20000000e+01]
 [ 1.05000000e+02  1.15000000e+02  3.20000000e+01  9.70000000e+01]
 [ 3.